### PR TITLE
Fix for Registering Accessory & Created config.schema.json

### PR DESCRIPTION
**Pull request by donavanbecker**
Log for homebridge

`Plugin 'homebridge-roomba-stv' tried to register with an incorrect plugin identifier: 'homebridge-roomba'. Please report this to the developer!`

### CODE REVIEW

**Comment by donavanbecker** [comment]
Also Created the config.schema.json for homebridge config ui x


Screen Shot 2020-05-12 at 9 34 44 AM

**Comment by donavanbecker** [comment]
I have created config.schema.json for config ui x/homebridge

Screen Shot 2020-05-12 at 9 35 58 AM

**Comment by donavanbecker** [comment]
@esteban-mallen would be awesome if this was merged.

**Review by esteban-mallen — APPROVED** [review]

**Comment by esteban-mallen** [comment]
Thank you so much for this!! @donavanbecker

**Comment by donavanbecker** [comment]
> Thank you so much for this!! @donavanbecker 

Thanks for merging!! You should apply for this plugin to be Homebridge [verified](https://github.com/homebridge/verified).

**Pull request merged**
